### ISSUE TITLE
Incorrect response MIME type. Expected 'application/wasm'

### ISSUE THREAD

**Issue by alwqx** [zyfdegh/gowasm-example#1]
Neither your code nor [WebAssembly wiki](https://github.com/golang/go/wiki/WebAssembly) can run,
error info on chrome console:
```
Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
```

**Comment by zyfdegh** [comment]
@adolphlwq Refresh the button page and make sure there's a `ContentType: application/wasm` header in the response of `GET http://localhost:8080/test.wasm`

**Comment by alwqx** [comment]
Thx, solved!
